### ISSUE TITLE
Style breaks sometimes

### ISSUE THREAD

**Issue by sedrubal** [mattermost/platform#5741]
#### Summary
Sometimes the stylle of mattermost breaks: highlights are totally yellow and unreadable, block code in markdown is rendered wrongly and colors are different to what they should be.

#### Steps to reproduce
- Use Firefox (version 51, 52)
- Use Mattermost (version 3.6.0 (?) bundled with GitLab 8.17.2)
- Wait until it breaks

#### Expected behavior
Style should look like this: 
![not broken](https://cloud.githubusercontent.com/assets/5571650/23833185/6ddce7f0-0742-11e7-8c2a-11ff7c996e29.png)

#### Observed behavior
But sometimes it looks like this:
![broken](https://cloud.githubusercontent.com/assets/5571650/23833206/b21a4c14-0742-11e7-9ea1-a7807280a00b.png)

This is the CSS I extracted using developer tools in Firefox. It's part of an inline style block:
```css
.post.post--comment .post__body {
  border-left:4px solid rgba(0,0,0,.3);
  padding-left:7px
}
.post.post--comment .post__body.mention-comment {
  border-left:4px solid #ff0;
  border-color:#ff0
}
```
